paths:
  data_root: "data"
  input_folder: "${paths.data_root}/input"
  processed_folder: "${paths.data_root}/processed"
  output_folder: "${paths.data_root}/output"
  ground_truth_folder: "${paths.data_root}/ground_truth"
  input_video: "${paths.input_folder}/video_21.mp4"

translation:
  target_language: "DA"