paths:
  data_root: "data"
  input_folder: "${paths.data_root}/input"
  processed_folder: "${paths.data_root}/processed"
  output_folder: "${paths.data_root}/output"
  input_video: "${paths.input_folder}/video_2.mp4"

models:
  whisper:
    model_name: "large-v3-turbo"

  demucs:
    model_name: "mdx_extra_q"

translation:
  target_language: "DA"

preprocessing:
  sample_rate: 44100
  channels: 2
  high_pass_freq: 80
  low_pass_freq: null

